sudo: required

language: php
php:
  - '5.6'
  - '7.0'

install:
  - composer install --no-scripts

script:
  - ./vendor/bin/phpcs --standard=psr2 --ignore=vendor -n .
  - ./vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_success:
  - ./vendor/bin/test-reporter

notifications:
  email: false
  slack:
    secure: k8clW99QW1LXlEHx3BtNFGtBP/kqFbYnZu9qZ7BKKaiEyE7/x3LlSCz2nRqGA50EXI9Ka/4gHe9rdTN9b9t2Ry+Q4Ja0+l8uwAZIVixc/RStdzFbMWSkt+vWIuuKGKEX3v/avs/VV17zEstCATFBeauELnrm9l07ReJX/ClFdgKxPlXHl26AbyRKFphd3dwe6yZJB6IceZCGYELMgMiccUkrpE363fRNjY7DdTF3dRKC9rfCcqhRQKSO4BCoTnaE+Aiyq2wd9AJCvI3hMbN6svDiU7mlv/b44gh4g9WeuJNDBNhvAwxvPSLiHzr+YoEkgvvfC7GYIL6KG9HaRIF3jPT+YGh7n98TpFxS83/4ZXejujm6Un2buT835I3UUAgGgjXI8m/c8UpeuyfBrV5valVPhT/W8toqT93E1AuKeKZZmiTYhULQV92+uZGaTpcdy/DotjPOyBjgwaoVJPsu6lm3L1IJ8DMGHpUYce72XS3Iw3IKdohJkZGGZCQjSc6/3FbXT64i1WF+q461GcGtlhDSuCv5RIwWBjZkQxU0Eg2DueJEjTk6xFTVGumA2Jh+f76xPr1Qw/NJT43mlT6qJb/T+VTJFPq+myknLu+lkMKzQR8Ej5x7Le/pN91jNs7JAZOoF3TVHHgezeptcq/eFwIMtGT/SwWXYmXkW6zzfII=
